plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

// Bundle the Layer 3 wrapper (node-wrapper/) into the APK assets so the sandbox
// can deploy it into the rootfs at first run (LinuxSandboxManager.deployWrapper).
// Emits into a generated build dir (NOT the tracked src tree) and registers it as
// an assets source below. node_modules is NOT bundled — `npm ci --omit=dev` runs
// inside Alpine, against the committed package-lock.json, after apk add nodejs npm.
val wrapperAssetsDir = layout.buildDirectory.dir("generated/wrapperAssets")
val copyWrapperAssets = tasks.register<Copy>("copyWrapperAssets") {
    from(rootProject.layout.projectDirectory.dir("../node-wrapper")) {
        include("src/**", "package.json", "package-lock.json")
        into("wrapper")
    }
    into(wrapperAssetsDir)
}

android {
    namespace = "industries.huginn.pifilling"
    compileSdk = 35

    defaultConfig {
        applicationId = "industries.huginn.pifilling"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0-dev"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // proot is shipped per-ABI as lib*.so under jniLibs (see sourceSets
        // below). Limit to the ABIs build-proot.sh actually produces.
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64")
        }
    }

    // Layer 2's cross-compiled proot binaries live in ../proot-bootstrap/.out/
    // as <abi>/lib*.so. Run `android/proot-bootstrap/build-proot.sh` before a
    // release build. The dir is wired in only when present so a UI-only debug
    // build still compiles on a machine that hasn't run the cross-compile yet.
    val prootOut = rootProject.layout.projectDirectory.dir("proot-bootstrap/.out")
    if (prootOut.asFile.exists()) {
        sourceSets["main"].jniLibs.srcDir(prootOut)
    }

    // The wrapper assets are generated by copyWrapperAssets into a build dir.
    sourceSets["main"].assets.srcDir(wrapperAssetsDir)

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
        debug {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    // proot ELF binaries are shipped as .so but are NOT real shared libraries;
    // do not let the packager compress or page-align them away.
    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

// Ensure the wrapper assets are copied before any build/asset-merge work.
tasks.named("preBuild").configure { dependsOn(copyWrapperAssets) }

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.activity.compose)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.androidx.material.icons.extended)

    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.android)

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))

    debugImplementation(libs.androidx.ui.tooling)
}
